Implement sparklyr changes for Databricks notebook-scoped libraries
sparklyr/sparklyr pull request #3147
Opened 2021-07-09 19:27 UTC by jlee2000

I am creating this PR to give sparklyr users a better experience on Databricks with respect to notebook-scoped libraries.

2021-07-09 19:53 UTC, falaki commented on R/databricks_connection.R
> +  # Hand in driver's libPaths to worker if user hasn't already set libpaths for notebook-scoped libraries
Can we add a unit test for this in https://github.com/sparklyr/sparklyr/blob/main/tests/testthat/test-databricks-connect.R?

2021-07-09 20:15 UTC, yitao-li requested changes
Looks good. :+1: Thanks for contributing to `sparklyr`!

- I hope this will address some pain points with Databricks use cases. Do you want to also update the `NEWS.md` file outlining the effect of this change, and also (maybe) briefly the rationale behind it?

- Also a question I have: does this make sense for all Databricks use cases? Are directory layouts on Spark driver and Spark worker noes guaranteed to be identical for notebook-scoped libs?

- Please see inline comment for suggestions on `toString()` and coding style in R.

2021-07-09 20:15 UTC, yitao-li commented on R/databricks_connection.R
> +    config$spark.r.libpaths <- toString(.libPaths())
We also typically shorten the `if (is.null(x)) x <- expr` type of assignment into `x <- x %||% expr` in `sparklyr` code base using the `%||%` operator from `rlang`.

2021-07-09 20:18 UTC, yitao-li commented on R/databricks_connection.R
> +  }
```suggestion
    config$spark.r.libpaths <- config$spark.r.libpaths %||% paste(.libPaths(), collapse = ",")
```

2021-07-09 20:18 UTC, yitao-li requested changes

2021-07-09 20:18 UTC, yitao-li commented on R/databricks_connection.R
> +  }
We also typically shorten the

```
if (is.null(x))
  x <- expr
```
type of assignment into `x <- x %||% expr` in sparklyr code base using the `%||%` operator from rlang.

2021-07-09 20:45 UTC, jlee2000 commented on R/databricks_connection.R
> +    config$spark.r.libpaths <- toString(.libPaths())
You're right, that works much better.

2021-07-09 21:02 UTC, jlee2000 commented
@yitao-li Thank you for the comments! They were very helpful. To answer your question: yes, this makes sense for Databricks use cases. The directory layout for workers and drivers is guaranteed to be the same.

2021-07-09 21:57 UTC, falaki approved these changes

2021-07-09 21:57 UTC, falaki commented on NEWS.md
> +- Added support for notebook-scoped libraries on Databricks connections.
```suggestion
- Added support for notebook-scoped libraries on Databricks.
```

2021-07-10 00:07 UTC, yitao-li approved these changes
LGTM :slightly_smiling_face:

2021-07-12 11:58 UTC, merged